[package]
name = "augmented-ui"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
wisual-logger = "0.1"
xml-rs = "0.8.4"
stretch = "0.3"
cocoa = "0.24"
objc = "0.2"
lazy_static = "1.4"

[package.metadata]
skip = true
