// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.78.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

abstract class Metronome {
  Future<int> initialize({required InitializeOptions options, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitializeConstMeta;

  Future<int> deinitialize({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDeinitializeConstMeta;

  Future<int> setIsPlaying({required bool value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetIsPlayingConstMeta;

  Future<int> setTempo({required double value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetTempoConstMeta;

  Future<int> setVolume({required double value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetVolumeConstMeta;

  Future<int> setBeatsPerBar({required int value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetBeatsPerBarConstMeta;

  Future<int> setSound({required MetronomeSoundTypeTag value, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSetSoundConstMeta;

  Future<double> getPlayhead({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetPlayheadConstMeta;
}

class InitializeOptions {
  final String? assetsFilePath;

  const InitializeOptions({
    this.assetsFilePath,
  });
}

enum MetronomeSoundTypeTag {
  Sine,
  Tube,
  Glass,
  Snap,
}

class MetronomeImpl implements Metronome {
  final MetronomePlatform _platform;
  factory MetronomeImpl(ExternalLibrary dylib) =>
      MetronomeImpl.raw(MetronomePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory MetronomeImpl.wasm(FutureOr<WasmModule> module) =>
      MetronomeImpl(module as ExternalLibrary);
  MetronomeImpl.raw(this._platform);
  Future<int> initialize({required InitializeOptions options, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_initialize_options(options);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_initialize(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kInitializeConstMeta,
      argValues: [options],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "initialize",
        argNames: ["options"],
      );

  Future<int> deinitialize({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_deinitialize(port_),
      parseSuccessData: _wire2api_i32,
      constMeta: kDeinitializeConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kDeinitializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "deinitialize",
        argNames: [],
      );

  Future<int> setIsPlaying({required bool value, dynamic hint}) {
    var arg0 = value;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_is_playing(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kSetIsPlayingConstMeta,
      argValues: [value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetIsPlayingConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_is_playing",
        argNames: ["value"],
      );

  Future<int> setTempo({required double value, dynamic hint}) {
    var arg0 = api2wire_f32(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_tempo(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kSetTempoConstMeta,
      argValues: [value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetTempoConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_tempo",
        argNames: ["value"],
      );

  Future<int> setVolume({required double value, dynamic hint}) {
    var arg0 = api2wire_f32(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_volume(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kSetVolumeConstMeta,
      argValues: [value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetVolumeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_volume",
        argNames: ["value"],
      );

  Future<int> setBeatsPerBar({required int value, dynamic hint}) {
    var arg0 = api2wire_i32(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_beats_per_bar(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kSetBeatsPerBarConstMeta,
      argValues: [value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetBeatsPerBarConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_beats_per_bar",
        argNames: ["value"],
      );

  Future<int> setSound({required MetronomeSoundTypeTag value, dynamic hint}) {
    var arg0 = api2wire_metronome_sound_type_tag(value);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_set_sound(port_, arg0),
      parseSuccessData: _wire2api_i32,
      constMeta: kSetSoundConstMeta,
      argValues: [value],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSetSoundConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "set_sound",
        argNames: ["value"],
      );

  Future<double> getPlayhead({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_playhead(port_),
      parseSuccessData: _wire2api_f32,
      constMeta: kGetPlayheadConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetPlayheadConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_playhead",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  double _wire2api_f32(dynamic raw) {
    return raw as double;
  }

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

@protected
double api2wire_f32(double raw) {
  return raw;
}

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_metronome_sound_type_tag(MetronomeSoundTypeTag raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class MetronomePlatform extends FlutterRustBridgeBase<MetronomeWire> {
  MetronomePlatform(ffi.DynamicLibrary dylib) : super(MetronomeWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_InitializeOptions> api2wire_box_autoadd_initialize_options(
      InitializeOptions raw) {
    final ptr = inner.new_box_autoadd_initialize_options_0();
    _api_fill_to_wire_initialize_options(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_opt_String(String? raw) {
    return raw == null ? ffi.nullptr : api2wire_String(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_initialize_options(
      InitializeOptions apiObj, ffi.Pointer<wire_InitializeOptions> wireObj) {
    _api_fill_to_wire_initialize_options(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_initialize_options(
      InitializeOptions apiObj, wire_InitializeOptions wireObj) {
    wireObj.assets_file_path = api2wire_opt_String(apiObj.assetsFilePath);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class MetronomeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MetronomeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MetronomeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void metronome_will_terminate() {
    return _metronome_will_terminate();
  }

  late final _metronome_will_terminatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'metronome_will_terminate');
  late final _metronome_will_terminate =
      _metronome_will_terminatePtr.asFunction<void Function()>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_initialize(
    int port_,
    ffi.Pointer<wire_InitializeOptions> options,
  ) {
    return _wire_initialize(
      port_,
      options,
    );
  }

  late final _wire_initializePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_InitializeOptions>)>>('wire_initialize');
  late final _wire_initialize = _wire_initializePtr
      .asFunction<void Function(int, ffi.Pointer<wire_InitializeOptions>)>();

  void wire_deinitialize(
    int port_,
  ) {
    return _wire_deinitialize(
      port_,
    );
  }

  late final _wire_deinitializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_deinitialize');
  late final _wire_deinitialize =
      _wire_deinitializePtr.asFunction<void Function(int)>();

  void wire_set_is_playing(
    int port_,
    bool value,
  ) {
    return _wire_set_is_playing(
      port_,
      value,
    );
  }

  late final _wire_set_is_playingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Bool)>>(
          'wire_set_is_playing');
  late final _wire_set_is_playing =
      _wire_set_is_playingPtr.asFunction<void Function(int, bool)>();

  void wire_set_tempo(
    int port_,
    double value,
  ) {
    return _wire_set_tempo(
      port_,
      value,
    );
  }

  late final _wire_set_tempoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'wire_set_tempo');
  late final _wire_set_tempo =
      _wire_set_tempoPtr.asFunction<void Function(int, double)>();

  void wire_set_volume(
    int port_,
    double value,
  ) {
    return _wire_set_volume(
      port_,
      value,
    );
  }

  late final _wire_set_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'wire_set_volume');
  late final _wire_set_volume =
      _wire_set_volumePtr.asFunction<void Function(int, double)>();

  void wire_set_beats_per_bar(
    int port_,
    int value,
  ) {
    return _wire_set_beats_per_bar(
      port_,
      value,
    );
  }

  late final _wire_set_beats_per_barPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'wire_set_beats_per_bar');
  late final _wire_set_beats_per_bar =
      _wire_set_beats_per_barPtr.asFunction<void Function(int, int)>();

  void wire_set_sound(
    int port_,
    int value,
  ) {
    return _wire_set_sound(
      port_,
      value,
    );
  }

  late final _wire_set_soundPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'wire_set_sound');
  late final _wire_set_sound =
      _wire_set_soundPtr.asFunction<void Function(int, int)>();

  void wire_get_playhead(
    int port_,
  ) {
    return _wire_get_playhead(
      port_,
    );
  }

  late final _wire_get_playheadPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_get_playhead');
  late final _wire_get_playhead =
      _wire_get_playheadPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_InitializeOptions> new_box_autoadd_initialize_options_0() {
    return _new_box_autoadd_initialize_options_0();
  }

  late final _new_box_autoadd_initialize_options_0Ptr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_InitializeOptions> Function()>>(
      'new_box_autoadd_initialize_options_0');
  late final _new_box_autoadd_initialize_options_0 =
      _new_box_autoadd_initialize_options_0Ptr
          .asFunction<ffi.Pointer<wire_InitializeOptions> Function()>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();

  int JNI_OnLoad(
    int vm,
    ffi.Pointer<ffi.Void> res,
  ) {
    return _JNI_OnLoad(
      vm,
      res,
    );
  }

  late final _JNI_OnLoadPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Void>)>>(
      'JNI_OnLoad');
  late final _JNI_OnLoad =
      _JNI_OnLoadPtr.asFunction<int Function(int, ffi.Pointer<ffi.Void>)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_InitializeOptions extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> assets_file_path;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
