[package]
name = "audio-processor-standalone-osc"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
wisual-logger = "0.1"
log = "^0.4.14"
rosc = "0.9.0"
hostname = "0.3.1"
thiserror = "^1.0.25"
