[package]
name = "augmented-audio-wave"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
skia-safe = { version = "0.54.0", features = ["metal"] }
audio-processor-traits = { version = "2", path = "../../audio/audio-processor-traits" }
log = "0.4.17"
audio-processor-analysis = { version = "0.3", path = "../../audio/audio-processor-analysis" }
audio-garbage-collector = { version = "1", path = "../../audio/audio-garbage-collector" }

[dev-dependencies]

audio-processor-testing-helpers = { version = "1", path = "../../testing/audio-processor-testing-helpers" }
audio-processor-file = { version = "1", path = "../../audio/audio-processor-file" }
wisual-logger = { version = "0.1.4", path = "../../ops/wisual-logger" }
foreign-types-shared = "0.1"
cocoa = "0.24.0"
core-graphics-types = "0.1.1"
objc = "*"
metal = "0.24.0"
winit = "0.27.3"
