[package]
name = "macos-bundle-resources"
version = "0.1.0"
edition = "2018"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
log = "^0.4.14"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "^0.9.1"
core-foundation-sys = "^0.8.2"