[package]
name = "lame-mp3"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
