name: augmented_midi_editor
description: MIDI editor GUI
version: 0.0.1
homepage: https://github.com/yamadapc/augmented-audio

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphx: ^1.0.3
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2

flutter:
