default_platform(:mac)

api_key_path = "../secret/apple_api_key.json"

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(api_key_path: api_key_path)
  end
end
